# Generated by Django 2.2.10 on 2020-09-16 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200914_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answar', to='api.Choice'),
        ),
        migrations.AlterField(
            model_name='question',
            name='assaignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='api.Assaignment'),
        ),
        migrations.AlterField(
            model_name='question',
            name='choices',
            field=models.ManyToManyField(blank=True, null=True, to='api.Choice'),
        ),
        migrations.AlterField(
            model_name='question',
            name='ordering',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.CharField(blank=True, max_length=245, null=True),
        ),
    ]
